workflows:
  ios-build:
    name: iOS Build Workflow
    platform :ios, '15.5'
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install
      - name: Build iOS
        script: flutter build ios --debug
    artifacts:
      - build/ios/ipa/*.ipa
